### ISSUE TITLE
Python 3.4: TypeError: key: expected bytes or bytearray, but got 'tuple'

### ISSUE THREAD

**Issue by DakotaNelson** [mitsuhiko/itsdangerous#41]
```
Traceback (most recent call last):
  File "---/venv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "---/htt-api/venv/lib/python3.4/site-packages/flask/app.py", line 1813, in wsgi_app
    ctx.push()
  File "---/venv/lib/python3.4/site-packages/flask/ctx.py", line 321, in push
    self.session = self.app.open_session(self.request)
  File "---/venv/lib/python3.4/site-packages/flask/app.py", line 825, in open_session
    return self.session_interface.open_session(self, request)
  File "---/venv/lib/python3.4/site-packages/flask/sessions.py", line 310, in open_session
    data = s.loads(val, max_age=max_age)
  File "---/venv/lib/python3.4/site-packages/itsdangerous.py", line 643, in loads
    .unsign(s, max_age, return_timestamp=True)
  File "---/venv/lib/python3.4/site-packages/itsdangerous.py", line 422, in unsign
    result = Signer.unsign(self, value)
  File "---/venv/lib/python3.4/site-packages/itsdangerous.py", line 371, in unsign
    if self.verify_signature(value, sig):
  File "---/venv/lib/python3.4/site-packages/itsdangerous.py", line 357, in verify_signature
    key = self.derive_key()
  File "---/venv/lib/python3.4/site-packages/itsdangerous.py", line 336, in derive_key
    mac = hmac.new(self.secret_key, digestmod=self.digest_method)
  File "/usr/lib64/python3.4/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib64/python3.4/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'tuple'
```

I suspect this is due to hmac changes in 3.4: https://docs.python.org/3/library/hmac.html

> hmac.new(key, msg=None, digestmod=None)

> Return a new hmac object. key is a bytes or bytearray object giving the secret key. If msg is present, the method call update(msg) is made. digestmod is the digest name, digest constructor or module for the HMAC object to use. It supports any name suitable to hashlib.new() and defaults to the hashlib.md5 constructor.

> Changed in version 3.4: Parameter key can be a bytes or bytearray object. Parameter msg can be of any type supported by hashlib. Parameter digestmod can be the name of a hash algorithm.

> Deprecated since version 3.4: MD5 as implicit default digest for digestmod is deprecated.

This prevents visiting _any_ of the routes in Flask, not just those which require login, which I would consider a pretty major problem.

**Comment by DakotaNelson** [comment]
Resolved: if the line defining `SECRET_KEY` in your configuration file has a trailing comma, terrible things will occur.

**Comment by kiptoomm** [comment]
I also experienced this error, and it turns out it was because my `SECRET_KEY` line was missing. A somewhat misleading one...

**Comment by erick-q42** [comment]
> Resolved: if the line defining `SECRET_KEY` in your configuration file has a trailing comma, terrible things will occur.

Thanks
